# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f76b141229d9084bfcb32d873db5035f7a4104f0a3e45d89384408c4b50ce34066b99c8fa333edb6d8131f7a98782678255195bcbb1da2eb1bb57ca7fe324e6f

test:
  secret_key_base: bbb9014df1ed33bb529ae925789b119de33b89efd73974fd83ed0aa5fd95c705313809251f1c8e0d42b8870dcc53b643fafd92e90e034553de6957bd20704c31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
